const SHORT_MOVIE_DURATION_IN_MIN = 40;

const DESKTOP_INITIAL_CARDS_NUMBER = 12;
const TABLET_INITIAL_CARDS_NUMBER = 8;
const MOBILE_INITIAL_CARDS_NUMBER = 5;

const MOBILE_WINDOW_SIZE = 480;
const TABLET_WINDOW_SIZE = 768;

const DESKTOP_LOAD_MORE_CARDS = 3;
const TABLET_LOAD_MORE_CARDS = 2;
const MOBILE_LOAD_MORE_CARDS = 2;

export {
  SHORT_MOVIE_DURATION_IN_MIN,
  DESKTOP_INITIAL_CARDS_NUMBER,
  TABLET_INITIAL_CARDS_NUMBER,
  MOBILE_INITIAL_CARDS_NUMBER,
  MOBILE_WINDOW_SIZE,
  TABLET_WINDOW_SIZE,
  DESKTOP_LOAD_MORE_CARDS,
  TABLET_LOAD_MORE_CARDS,
  MOBILE_LOAD_MORE_CARDS
}